[project]
name = "image2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "betterproto[compiler]>=1.2.5",
    "grpcio-tools>=1.76.0",
    "grpclib>=0.4.9",
    "pillow>=12.0.0",
]
